#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/nokia/DDV

PRODUCT_COPY_FILES += \
    vendor/nokia/DDV/proprietary/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/QRD_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_workspaceFile.qwsp \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Bluetooth_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_General_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Global_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Handset_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Hdmi_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Headset_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Speaker_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_workspaceFile.qwsp \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Bluetooth_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_General_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Global_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Handset_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Hdmi_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Headset_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Speaker_cal.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_workspaceFile.qwsp \
    vendor/nokia/DDV/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/M_Classify_Cnn_5.3.5.model.hardcode:$(TARGET_COPY_OUT_VENDOR)/etc/camera/M_Classify_Cnn_5.3.5.model.hardcode \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/butterfly.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/butterfly.bin \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/csidtg_camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_camera.xml \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/csidtg_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_chromatix.xml \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/daredevil_gc5035_aux_truly_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/daredevil_gc5035_aux_truly_ii_chromatix.xml \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/daredevil_gc8034_wide_byd_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/daredevil_gc8034_wide_byd_ii_chromatix.xml \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/daredevil_hi2021q_front_tsp_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/daredevil_hi2021q_front_tsp_ii_chromatix.xml \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/daredevil_hi556_aux_tsp_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/daredevil_hi556_aux_tsp_i_chromatix.xml \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/daredevil_hi846_wide_txd_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/daredevil_hi846_wide_txd_i_chromatix.xml \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/daredevil_s5k3t1sp_front_tru_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/daredevil_s5k3t1sp_front_tru_ii_chromatix.xml \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/daredevil_s5k3t1sp_front_tsp_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/daredevil_s5k3t1sp_front_tsp_i_chromatix.xml \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/daredevil_s5kgm1sp_back_tly_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/daredevil_s5kgm1sp_back_tly_ii_chromatix.xml \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/daredevil_s5kgm1sp_back_tsp_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/daredevil_s5kgm1sp_back_tsp_i_chromatix.xml \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/flake.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/flake.bin \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/heart.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/heart.bin \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/ncf/frontcam/ISO100_2584x1938.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ncf/frontcam/ISO100_2584x1938.ncf \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/ncf/frontcam/ISO1600_2584x1938.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ncf/frontcam/ISO1600_2584x1938.ncf \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/ncf/frontcam/ISO200_2584x1938.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ncf/frontcam/ISO200_2584x1938.ncf \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/ncf/frontcam/ISO3200_2584x1938.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ncf/frontcam/ISO3200_2584x1938.ncf \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/ncf/frontcam/ISO400_2584x1938.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ncf/frontcam/ISO400_2584x1938.ncf \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/ncf/frontcam/ISO6400_2584x1938.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ncf/frontcam/ISO6400_2584x1938.ncf \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/ncf/frontcam/ISO800_2584x1938.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ncf/frontcam/ISO800_2584x1938.ncf \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/ncf/rearcam/ISO100_4000x3000.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ncf/rearcam/ISO100_4000x3000.ncf \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/ncf/rearcam/ISO1600_4000x3000.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ncf/rearcam/ISO1600_4000x3000.ncf \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/ncf/rearcam/ISO200_4000x3000.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ncf/rearcam/ISO200_4000x3000.ncf \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/ncf/rearcam/ISO3200_4000x3000.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ncf/rearcam/ISO3200_4000x3000.ncf \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/ncf/rearcam/ISO400_4000x3000.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ncf/rearcam/ISO400_4000x3000.ncf \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/ncf/rearcam/ISO6400_4000x3000.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ncf/rearcam/ISO6400_4000x3000.ncf \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/ncf/rearcam/ISO800_4000x3000.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ncf/rearcam/ISO800_4000x3000.ncf \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/ncf/rearcam/ISO9600_4000x3000.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ncf/rearcam/ISO9600_4000x3000.ncf \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/star.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/star.bin \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/nokia/DDV/proprietary/vendor/etc/camera/waterdrop.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/waterdrop.bin \
    vendor/nokia/DDV/proprietary/vendor/etc/firmware/hx_criteria.csv:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/hx_criteria.csv \
    vendor/nokia/DDV/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/nokia/DDV/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-service-qti.rc \
    vendor/nokia/DDV/proprietary/vendor/etc/init/init_qfp_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_qfp_daemon.rc \
    vendor/nokia/DDV/proprietary/vendor/etc/init/vendor.fingerprint.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.fingerprint.rc \
    vendor/nokia/DDV/proprietary/vendor/etc/init/vendor.qti.hardware.soter@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.soter@1.0-service.rc \
    vendor/nokia/DDV/proprietary/vendor/etc/init/vendor.sw.swfingerprint@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sw.swfingerprint@1.0-service.rc \
    vendor/nokia/DDV/proprietary/vendor/etc/init/vendor.trustonic.tee@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.tee@1.0-service.rc \
    vendor/nokia/DDV/proprietary/vendor/etc/init/vendor.trustonic.teeregistry@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.teeregistry@1.0-service.rc \
    vendor/nokia/DDV/proprietary/vendor/etc/libnfc-sec-vendor.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-sec-vendor.conf \
    vendor/nokia/DDV/proprietary/vendor/etc/permissions/qti_fingerprint_interface.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/qti_fingerprint_interface.xml \
    vendor/nokia/DDV/proprietary/vendor/etc/public.libraries-trustonic.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries-trustonic.txt \
    vendor/nokia/DDV/proprietary/vendor/etc/sec_s3nrn82_rfreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/sec_s3nrn82_rfreg.bin \
    vendor/nokia/DDV/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/nokia/DDV/proprietary/vendor/firmware/AbovCapSense.BIN:$(TARGET_COPY_OUT_VENDOR)/firmware/AbovCapSense.BIN \
    vendor/nokia/DDV/proprietary/vendor/firmware/File_iris3_inParm11.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/File_iris3_inParm11.txt \
    vendor/nokia/DDV/proprietary/vendor/firmware/File_iris3_inParm2.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/File_iris3_inParm2.txt \
    vendor/nokia/DDV/proprietary/vendor/firmware/File_iris3_inParm5.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/File_iris3_inParm5.txt \
    vendor/nokia/DDV/proprietary/vendor/firmware/File_iris3_inParm8.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/File_iris3_inParm8.txt \
    vendor/nokia/DDV/proprietary/vendor/firmware/HLT-iris3.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/HLT-iris3.fw \
    vendor/nokia/DDV/proprietary/vendor/firmware/HLT_iris3_inParm11.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/HLT_iris3_inParm11.txt \
    vendor/nokia/DDV/proprietary/vendor/firmware/HLT_iris3_inParm2.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/HLT_iris3_inParm2.txt \
    vendor/nokia/DDV/proprietary/vendor/firmware/HLT_iris3_inParm5.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/HLT_iris3_inParm5.txt \
    vendor/nokia/DDV/proprietary/vendor/firmware/HLT_iris3_inParm8.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/HLT_iris3_inParm8.txt \
    vendor/nokia/DDV/proprietary/vendor/firmware/Himax_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Himax_firmware.bin \
    vendor/nokia/DDV/proprietary/vendor/firmware/a512_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b00 \
    vendor/nokia/DDV/proprietary/vendor/firmware/a512_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b01 \
    vendor/nokia/DDV/proprietary/vendor/firmware/a512_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b02 \
    vendor/nokia/DDV/proprietary/vendor/firmware/a512_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.elf \
    vendor/nokia/DDV/proprietary/vendor/firmware/a512_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.mdt \
    vendor/nokia/DDV/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/nokia/DDV/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/nokia/DDV/proprietary/vendor/firmware/cdfinger.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.b00 \
    vendor/nokia/DDV/proprietary/vendor/firmware/cdfinger.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.b01 \
    vendor/nokia/DDV/proprietary/vendor/firmware/cdfinger.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.b02 \
    vendor/nokia/DDV/proprietary/vendor/firmware/cdfinger.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.b03 \
    vendor/nokia/DDV/proprietary/vendor/firmware/cdfinger.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.b04 \
    vendor/nokia/DDV/proprietary/vendor/firmware/cdfinger.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.b05 \
    vendor/nokia/DDV/proprietary/vendor/firmware/cdfinger.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.b06 \
    vendor/nokia/DDV/proprietary/vendor/firmware/cdfinger.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.b07 \
    vendor/nokia/DDV/proprietary/vendor/firmware/cdfinger.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.mdt \
    vendor/nokia/DDV/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/nokia/DDV/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/nokia/DDV/proprietary/vendor/firmware/cpp_firmware_v1_12_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_1.fw \
    vendor/nokia/DDV/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/nokia/DDV/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/nokia/DDV/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/nokia/DDV/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/nokia/DDV/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/nokia/DDV/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/nokia/DDV/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/nokia/DDV/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/nokia/DDV/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/nokia/DDV/proprietary/vendor/firmware/iris3.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/iris3.fw \
    vendor/nokia/DDV/proprietary/vendor/firmware/iris3_ct_value:$(TARGET_COPY_OUT_VENDOR)/firmware/iris3_ct_value \
    vendor/nokia/DDV/proprietary/vendor/firmware/iris3_inParm11.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/iris3_inParm11.txt \
    vendor/nokia/DDV/proprietary/vendor/firmware/iris3_inParm2.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/iris3_inParm2.txt \
    vendor/nokia/DDV/proprietary/vendor/firmware/iris3_inParm5.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/iris3_inParm5.txt \
    vendor/nokia/DDV/proprietary/vendor/firmware/iris3_inParm8.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/iris3_inParm8.txt \
    vendor/nokia/DDV/proprietary/vendor/firmware/sec_s3nrn82_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sec_s3nrn82_firmware.bin \
    vendor/nokia/DDV/proprietary/vendor/firmware/sw_fp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/sw_fp.b00 \
    vendor/nokia/DDV/proprietary/vendor/firmware/sw_fp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/sw_fp.b01 \
    vendor/nokia/DDV/proprietary/vendor/firmware/sw_fp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/sw_fp.b02 \
    vendor/nokia/DDV/proprietary/vendor/firmware/sw_fp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/sw_fp.b03 \
    vendor/nokia/DDV/proprietary/vendor/firmware/sw_fp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/sw_fp.b04 \
    vendor/nokia/DDV/proprietary/vendor/firmware/sw_fp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/sw_fp.b05 \
    vendor/nokia/DDV/proprietary/vendor/firmware/sw_fp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/sw_fp.b06 \
    vendor/nokia/DDV/proprietary/vendor/firmware/sw_fp.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/sw_fp.b07 \
    vendor/nokia/DDV/proprietary/vendor/firmware/sw_fp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/sw_fp.mdt \
    vendor/nokia/DDV/proprietary/vendor/firmware/tbase.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/tbase.b00 \
    vendor/nokia/DDV/proprietary/vendor/firmware/tbase.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/tbase.b01 \
    vendor/nokia/DDV/proprietary/vendor/firmware/tbase.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/tbase.b02 \
    vendor/nokia/DDV/proprietary/vendor/firmware/tbase.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/tbase.b03 \
    vendor/nokia/DDV/proprietary/vendor/firmware/tbase.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/tbase.b04 \
    vendor/nokia/DDV/proprietary/vendor/firmware/tbase.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/tbase.b05 \
    vendor/nokia/DDV/proprietary/vendor/firmware/tbase.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/tbase.b06 \
    vendor/nokia/DDV/proprietary/vendor/firmware/tbase.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/tbase.b07 \
    vendor/nokia/DDV/proprietary/vendor/firmware/tbase.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/tbase.mdt

PRODUCT_PACKAGES += \
    swfingerprint.default \
    libMcClient \
    libarcsoft_beautyshot \
    libcapiv2svacnn \
    libcapiv2vop \
    libmmcamera2_frame_algorithm \
    libmmcamera2_is \
    libmmcamera2_q3a_core \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera_dbg \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmpbase \
    libremosaic_daemon \
    libseemore \
    libsensor1 \
    libsensor_reg \
    libssc_default_listener \
    libvideoutils \
    nfc_nci_sec \
    sensor_calibrate \
    sensors.ssc \
    vendor.sw.swfingerprint@1.0 \
    camera.sdm660 \
    vendor.sw.swfingerprint@1.0-impl \
    libactuator_ad5816g \
    libactuator_ad5823 \
    libactuator_ak7345 \
    libactuator_ak7371 \
    libactuator_bu64244gwz \
    libactuator_bu64297 \
    libactuator_daredevil_s5kgm1sp_back_tly_ii_gt9767 \
    libactuator_daredevil_s5kgm1sp_back_tsp_i_gt9767 \
    libactuator_dw9714 \
    libactuator_dw9716 \
    libactuator_dw9790a \
    libactuator_lc898122 \
    libactuator_lc898212xd \
    libactuator_lc898212xd_qc2002 \
    libactuator_lc898217xc \
    libactuator_pseudo \
    libactuator_rohm_bu64243gwz \
    libactuator_starlord_s5k3p9sx_back_hlt_ii_gt9767 \
    libactuator_starlord_s5k3p9sx_back_txd_i_gt9767 \
    libarcsoft_bokehplus_image \
    libarcsoft_bokehplus_video \
    libarcsoft_dro \
    libarcsoft_dualcam_superportrait_image_lite \
    libarcsoft_dualcam_superportrait_video_lite \
    libarcsoft_hdr_detection \
    libarcsoft_singlecam_bokeh \
    libarcsoft_singlecam_superportrait_lite \
    libarcsoft_smart_denoise \
    libarcsoft_supernight \
    libchromatix_csidtg_common \
    libchromatix_csidtg_cpp_preview \
    libchromatix_csidtg_postproc \
    libchromatix_csidtg_preview \
    libchromatix_csidtg_zsl_preview \
    libchromatix_daredevil_gc5035_aux_truly_ii_a3_default_preview \
    libchromatix_daredevil_gc5035_aux_truly_ii_a3_default_video \
    libchromatix_daredevil_gc5035_aux_truly_ii_a3_hfr_120 \
    libchromatix_daredevil_gc5035_aux_truly_ii_a3_hfr_60 \
    libchromatix_daredevil_gc5035_aux_truly_ii_a3_hfr_90 \
    libchromatix_daredevil_gc5035_aux_truly_ii_common \
    libchromatix_daredevil_gc5035_aux_truly_ii_cpp_ds_chromatix \
    libchromatix_daredevil_gc5035_aux_truly_ii_cpp_hfr_120 \
    libchromatix_daredevil_gc5035_aux_truly_ii_cpp_hfr_60 \
    libchromatix_daredevil_gc5035_aux_truly_ii_cpp_hfr_90 \
    libchromatix_daredevil_gc5035_aux_truly_ii_cpp_liveshot \
    libchromatix_daredevil_gc5035_aux_truly_ii_cpp_preview \
    libchromatix_daredevil_gc5035_aux_truly_ii_cpp_snapshot \
    libchromatix_daredevil_gc5035_aux_truly_ii_cpp_us_chromatix \
    libchromatix_daredevil_gc5035_aux_truly_ii_cpp_video \
    libchromatix_daredevil_gc5035_aux_truly_ii_cpp_video_full \
    libchromatix_daredevil_gc5035_aux_truly_ii_default_video \
    libchromatix_daredevil_gc5035_aux_truly_ii_hfr_120 \
    libchromatix_daredevil_gc5035_aux_truly_ii_hfr_60 \
    libchromatix_daredevil_gc5035_aux_truly_ii_hfr_90 \
    libchromatix_daredevil_gc5035_aux_truly_ii_postproc \
    libchromatix_daredevil_gc5035_aux_truly_ii_preview \
    libchromatix_daredevil_gc5035_aux_truly_ii_snapshot \
    libchromatix_daredevil_gc5035_aux_truly_ii_video_full \
    libchromatix_daredevil_gc5035_aux_truly_ii_zsl_preview \
    libchromatix_daredevil_gc5035_aux_truly_ii_zsl_video \
    libchromatix_daredevil_gc8034_wide_byd_ii_a3_default_preview \
    libchromatix_daredevil_gc8034_wide_byd_ii_a3_default_video \
    libchromatix_daredevil_gc8034_wide_byd_ii_a3_hfr_120 \
    libchromatix_daredevil_gc8034_wide_byd_ii_a3_hfr_60 \
    libchromatix_daredevil_gc8034_wide_byd_ii_a3_hfr_90 \
    libchromatix_daredevil_gc8034_wide_byd_ii_common \
    libchromatix_daredevil_gc8034_wide_byd_ii_cpp_ds_chromatix \
    libchromatix_daredevil_gc8034_wide_byd_ii_cpp_hfr_120 \
    libchromatix_daredevil_gc8034_wide_byd_ii_cpp_hfr_60 \
    libchromatix_daredevil_gc8034_wide_byd_ii_cpp_hfr_90 \
    libchromatix_daredevil_gc8034_wide_byd_ii_cpp_liveshot \
    libchromatix_daredevil_gc8034_wide_byd_ii_cpp_preview \
    libchromatix_daredevil_gc8034_wide_byd_ii_cpp_snapshot \
    libchromatix_daredevil_gc8034_wide_byd_ii_cpp_us_chromatix \
    libchromatix_daredevil_gc8034_wide_byd_ii_cpp_video \
    libchromatix_daredevil_gc8034_wide_byd_ii_default_video \
    libchromatix_daredevil_gc8034_wide_byd_ii_hfr_120 \
    libchromatix_daredevil_gc8034_wide_byd_ii_hfr_60 \
    libchromatix_daredevil_gc8034_wide_byd_ii_hfr_90 \
    libchromatix_daredevil_gc8034_wide_byd_ii_liveshot \
    libchromatix_daredevil_gc8034_wide_byd_ii_postproc \
    libchromatix_daredevil_gc8034_wide_byd_ii_preview \
    libchromatix_daredevil_gc8034_wide_byd_ii_snapshot \
    libchromatix_daredevil_gc8034_wide_byd_ii_zsl_preview \
    libchromatix_daredevil_gc8034_wide_byd_ii_zsl_video \
    libchromatix_daredevil_hi2021q_front_tsp_ii_beauty_preview_3a \
    libchromatix_daredevil_hi2021q_front_tsp_ii_bokeh_preview \
    libchromatix_daredevil_hi2021q_front_tsp_ii_bokeh_snapshot \
    libchromatix_daredevil_hi2021q_front_tsp_ii_common \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_liveshot \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_preview \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_preview_beauty \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_preview_bokeh \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_preview_pro \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_snapshot \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_snapshot_12m \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_snapshot_15m \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_snapshot_20m \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_snapshot_5M \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_snapshot_5M_hht \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_snapshot_beauty \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_snapshot_bokeh \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_snapshot_downscale \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_snapshot_hdr \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_snapshot_pro \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_snapshot_upscale \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_video \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_video_1080p \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_video_720p \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_video_default \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_video_face \
    libchromatix_daredevil_hi2021q_front_tsp_ii_cpp_video_weixin \
    libchromatix_daredevil_hi2021q_front_tsp_ii_default_bokeh_preview_3a \
    libchromatix_daredevil_hi2021q_front_tsp_ii_default_preview_3a \
    libchromatix_daredevil_hi2021q_front_tsp_ii_default_video_3a \
    libchromatix_daredevil_hi2021q_front_tsp_ii_face_video_3a \
    libchromatix_daredevil_hi2021q_front_tsp_ii_fullsize_preview_3a \
    libchromatix_daredevil_hi2021q_front_tsp_ii_fullsize_video_3a \
    libchromatix_daredevil_hi2021q_front_tsp_ii_hdr_preview_3a \
    libchromatix_daredevil_hi2021q_front_tsp_ii_hdr_video_3a \
    libchromatix_daredevil_hi2021q_front_tsp_ii_its_preview_3a \
    libchromatix_daredevil_hi2021q_front_tsp_ii_postproc \
    libchromatix_daredevil_hi2021q_front_tsp_ii_preview \
    libchromatix_daredevil_hi2021q_front_tsp_ii_snapshot \
    libchromatix_daredevil_hi2021q_front_tsp_ii_snapshot_beauty \
    libchromatix_daredevil_hi2021q_front_tsp_ii_snapshot_hdr \
    libchromatix_daredevil_hi2021q_front_tsp_ii_video_default \
    libchromatix_daredevil_hi2021q_front_tsp_ii_video_face \
    libchromatix_daredevil_hi2021q_front_tsp_ii_video_weixin \
    libchromatix_daredevil_hi2021q_front_tsp_ii_weixin_video_3a \
    libchromatix_daredevil_hi556_aux_tsp_i_3a_ai_scence_1 \
    libchromatix_daredevil_hi556_aux_tsp_i_3a_ai_scence_2 \
    libchromatix_daredevil_hi556_aux_tsp_i_3a_ai_scence_3 \
    libchromatix_daredevil_hi556_aux_tsp_i_3a_ai_scence_4 \
    libchromatix_daredevil_hi556_aux_tsp_i_3a_ai_scence_5 \
    libchromatix_daredevil_hi556_aux_tsp_i_3a_ai_scence_6 \
    libchromatix_daredevil_hi556_aux_tsp_i_3a_ai_scence_7 \
    libchromatix_daredevil_hi556_aux_tsp_i_a3_default_preview \
    libchromatix_daredevil_hi556_aux_tsp_i_a3_default_video \
    libchromatix_daredevil_hi556_aux_tsp_i_a3_hfr_120 \
    libchromatix_daredevil_hi556_aux_tsp_i_a3_hfr_60 \
    libchromatix_daredevil_hi556_aux_tsp_i_a3_hfr_90 \
    libchromatix_daredevil_hi556_aux_tsp_i_common \
    libchromatix_daredevil_hi556_aux_tsp_i_cpp_ds_chromatix \
    libchromatix_daredevil_hi556_aux_tsp_i_cpp_hfr_120 \
    libchromatix_daredevil_hi556_aux_tsp_i_cpp_hfr_60 \
    libchromatix_daredevil_hi556_aux_tsp_i_cpp_hfr_90 \
    libchromatix_daredevil_hi556_aux_tsp_i_cpp_liveshot \
    libchromatix_daredevil_hi556_aux_tsp_i_cpp_preview \
    libchromatix_daredevil_hi556_aux_tsp_i_cpp_scence_1 \
    libchromatix_daredevil_hi556_aux_tsp_i_cpp_scence_2 \
    libchromatix_daredevil_hi556_aux_tsp_i_cpp_scence_3 \
    libchromatix_daredevil_hi556_aux_tsp_i_cpp_scence_4 \
    libchromatix_daredevil_hi556_aux_tsp_i_cpp_scence_5 \
    libchromatix_daredevil_hi556_aux_tsp_i_cpp_scence_6 \
    libchromatix_daredevil_hi556_aux_tsp_i_cpp_scence_7 \
    libchromatix_daredevil_hi556_aux_tsp_i_cpp_snapshot \
    libchromatix_daredevil_hi556_aux_tsp_i_cpp_us_chromatix \
    libchromatix_daredevil_hi556_aux_tsp_i_cpp_video \
    libchromatix_daredevil_hi556_aux_tsp_i_cpp_video_full \
    libchromatix_daredevil_hi556_aux_tsp_i_default_video \
    libchromatix_daredevil_hi556_aux_tsp_i_hfr_120 \
    libchromatix_daredevil_hi556_aux_tsp_i_hfr_60 \
    libchromatix_daredevil_hi556_aux_tsp_i_hfr_90 \
    libchromatix_daredevil_hi556_aux_tsp_i_isp_scence_1 \
    libchromatix_daredevil_hi556_aux_tsp_i_isp_scence_2 \
    libchromatix_daredevil_hi556_aux_tsp_i_isp_scence_3 \
    libchromatix_daredevil_hi556_aux_tsp_i_isp_scence_4 \
    libchromatix_daredevil_hi556_aux_tsp_i_isp_scence_5 \
    libchromatix_daredevil_hi556_aux_tsp_i_isp_scence_6 \
    libchromatix_daredevil_hi556_aux_tsp_i_isp_scence_7 \
    libchromatix_daredevil_hi556_aux_tsp_i_liveshot \
    libchromatix_daredevil_hi556_aux_tsp_i_postproc \
    libchromatix_daredevil_hi556_aux_tsp_i_preview \
    libchromatix_daredevil_hi556_aux_tsp_i_snapshot \
    libchromatix_daredevil_hi556_aux_tsp_i_video_full \
    libchromatix_daredevil_hi556_aux_tsp_i_zsl_preview \
    libchromatix_daredevil_hi556_aux_tsp_i_zsl_video \
    libchromatix_daredevil_hi846_wide_txd_i_3a_ai_scence_1 \
    libchromatix_daredevil_hi846_wide_txd_i_3a_ai_scence_2 \
    libchromatix_daredevil_hi846_wide_txd_i_3a_ai_scence_3 \
    libchromatix_daredevil_hi846_wide_txd_i_3a_ai_scence_4 \
    libchromatix_daredevil_hi846_wide_txd_i_3a_ai_scence_5 \
    libchromatix_daredevil_hi846_wide_txd_i_3a_ai_scence_6 \
    libchromatix_daredevil_hi846_wide_txd_i_3a_ai_scence_7 \
    libchromatix_daredevil_hi846_wide_txd_i_a3_default_preview \
    libchromatix_daredevil_hi846_wide_txd_i_a3_default_video \
    libchromatix_daredevil_hi846_wide_txd_i_a3_hfr_120 \
    libchromatix_daredevil_hi846_wide_txd_i_beauty_preview_3a \
    libchromatix_daredevil_hi846_wide_txd_i_common \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_hfr_120 \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_liveshot \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_preview \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_preview_sn \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_scence_1 \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_scence_2 \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_scence_3 \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_scence_4 \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_scence_5 \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_scence_6 \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_scence_7 \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_snapshot \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_snapshot_5m \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_snapshot_6m \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_snapshot_beauty \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_snapshot_hht \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_snapshot_sn \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_video \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_video_1080p \
    libchromatix_daredevil_hi846_wide_txd_i_cpp_video_720p \
    libchromatix_daredevil_hi846_wide_txd_i_default_video \
    libchromatix_daredevil_hi846_wide_txd_i_hfr_120 \
    libchromatix_daredevil_hi846_wide_txd_i_isp_scence_1 \
    libchromatix_daredevil_hi846_wide_txd_i_isp_scence_2 \
    libchromatix_daredevil_hi846_wide_txd_i_isp_scence_3 \
    libchromatix_daredevil_hi846_wide_txd_i_isp_scence_4 \
    libchromatix_daredevil_hi846_wide_txd_i_isp_scence_5 \
    libchromatix_daredevil_hi846_wide_txd_i_isp_scence_6 \
    libchromatix_daredevil_hi846_wide_txd_i_isp_scence_7 \
    libchromatix_daredevil_hi846_wide_txd_i_liveshot \
    libchromatix_daredevil_hi846_wide_txd_i_postproc \
    libchromatix_daredevil_hi846_wide_txd_i_preview \
    libchromatix_daredevil_hi846_wide_txd_i_snapshot \
    libchromatix_daredevil_hi846_wide_txd_i_snapshot_beauty \
    libchromatix_daredevil_hi846_wide_txd_i_snapshot_sn \
    libchromatix_daredevil_hi846_wide_txd_i_zsl_preview \
    libchromatix_daredevil_hi846_wide_txd_i_zsl_preview_3a_sn \
    libchromatix_daredevil_hi846_wide_txd_i_zsl_video \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_bokeh_preview \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_bokeh_snapshot \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_common \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_cpp_liveshot \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_cpp_preview \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_cpp_snapshot \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_cpp_snapshot_5M \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_cpp_snapshot_5M_hht \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_cpp_snapshot_bokeh \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_cpp_snapshot_downscale \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_cpp_snapshot_hdr \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_cpp_snapshot_upscale \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_cpp_video \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_cpp_video_default \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_cpp_video_face \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_cpp_video_weixin \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_default_bokeh_preview_3a \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_default_preview_3a \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_default_video_3a \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_face_video_3a \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_fullsize_preview_3a \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_fullsize_video_3a \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_hdr_preview_3a \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_hdr_video_3a \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_postproc \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_preview \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_snapshot \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_snapshot_hdr \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_video_default \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_video_face \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_video_weixin \
    libchromatix_daredevil_s5k3t1sp_front_tru_ii_weixin_video_3a \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_3a_ai_scence_1 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_3a_ai_scence_2 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_3a_ai_scence_3 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_3a_ai_scence_4 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_3a_ai_scence_5 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_3a_ai_scence_6 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_3a_ai_scence_7 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_beauty_preview_3a \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_bokeh_preview \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_bokeh_snapshot \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_common \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_liveshot \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_preview \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_preview_beauty \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_preview_bokeh \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_preview_pro \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_scence_1 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_scence_2 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_scence_3 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_scence_4 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_scence_5 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_scence_6 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_scence_7 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_snapshot \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_snapshot_12m \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_snapshot_15m \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_snapshot_20m \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_snapshot_5M \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_snapshot_5M_hht \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_snapshot_beauty \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_snapshot_bokeh \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_snapshot_downscale \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_snapshot_hdr \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_snapshot_pro \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_snapshot_upscale \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_video \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_video_1080p \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_video_720p \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_video_default \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_video_face \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_cpp_video_weixin \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_default_bokeh_preview_3a \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_default_preview_3a \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_default_video_3a \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_face_video_3a \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_fullsize_preview_3a \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_fullsize_video_3a \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_hdr_preview_3a \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_hdr_video_3a \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_isp_scence_1 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_isp_scence_2 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_isp_scence_3 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_isp_scence_4 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_isp_scence_5 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_isp_scence_6 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_isp_scence_7 \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_its_preview_3a \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_postproc \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_preview \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_snapshot \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_snapshot_beauty \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_snapshot_hdr \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_video_default \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_video_face \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_video_weixin \
    libchromatix_daredevil_s5k3t1sp_front_tsp_i_weixin_video_3a \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_3a_ai_scence_1 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_3a_ai_scence_2 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_3a_ai_scence_3 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_3a_ai_scence_4 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_3a_ai_scence_5 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_3a_ai_scence_6 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_3a_ai_scence_7 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_4k_preview_3a \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_4k_video_3a \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_beauty_preview_3a \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_bokeh_preview_3a \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_common \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_hfr_120 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_hfr_60 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_hfr_90 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_liveshot \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_preview \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_preview_sn \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_preview_sr \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_preview_video \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_scence_1 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_scence_2 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_scence_3 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_scence_4 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_scence_5 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_scence_6 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_scence_7 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_snapshot \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_snapshot_beauty \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_snapshot_bokeh \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_snapshot_hdr \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_snapshot_hht \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_snapshot_panorama \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_snapshot_sn \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_snapshot_sr \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_video \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_video_4k \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_video_weixin \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_cpp_video_weixin_res1 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_default_preview_3a \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_default_video_3a \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_hfr_120 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_hfr_120_3a \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_hfr_60 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_hfr_60_3a \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_hfr_90 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_hfr_90_3a \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_isp_scence_1 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_isp_scence_2 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_isp_scence_3 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_isp_scence_4 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_isp_scence_5 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_isp_scence_6 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_isp_scence_7 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_pano_preview_3a \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_postproc \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_preview \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_preview_cts \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_snapshot \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_snapshot_beauty \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_snapshot_bokeh \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_snapshot_hdr \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_snapshot_panorama \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_snapshot_sn \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_video \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_video_4k \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_video_weixin \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_video_weixin_res1 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_weixin_video_3a \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_weixin_video_3a_res1 \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_zsl_preview_3a \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_zsl_preview_3a_sn \
    libchromatix_daredevil_s5kgm1sp_back_tly_ii_zsl_video_3a \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_3a_ai_scence_1 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_3a_ai_scence_2 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_3a_ai_scence_3 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_3a_ai_scence_4 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_3a_ai_scence_5 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_3a_ai_scence_6 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_3a_ai_scence_7 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_4k_preview_3a \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_4k_video_3a \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_beauty_preview_3a \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_bokeh_preview_3a \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_common \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_hfr_120 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_hfr_60 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_hfr_90 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_liveshot \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_preview \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_preview_48M \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_preview_pro \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_preview_sn \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_preview_sr \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_preview_video \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_scence_1 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_scence_2 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_scence_3 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_scence_4 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_scence_5 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_scence_6 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_scence_7 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_snapshot \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_snapshot_48m \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_snapshot_7m \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_snapshot_9m \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_snapshot_beauty \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_snapshot_bokeh \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_snapshot_hdr \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_snapshot_hht \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_snapshot_panorama \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_snapshot_pro \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_snapshot_sn \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_snapshot_sr \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_video \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_video_1080p \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_video_4k \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_video_720p \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_video_weixin \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_cpp_video_weixin_res1 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_default_preview_3a \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_default_video_3a \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_hfr_120 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_hfr_120_3a \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_hfr_60 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_hfr_60_3a \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_hfr_90 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_hfr_90_3a \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_isp_scence_1 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_isp_scence_2 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_isp_scence_3 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_isp_scence_4 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_isp_scence_5 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_isp_scence_6 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_isp_scence_7 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_pano_preview_3a \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_postproc \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_preview \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_preview_cts \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_snapshot \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_snapshot_beauty \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_snapshot_bokeh \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_snapshot_hdr \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_snapshot_its \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_snapshot_panorama \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_snapshot_sn \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_video \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_video_4k \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_video_weixin \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_video_weixin_res1 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_weixin_video_3a \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_weixin_video_3a_res1 \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_zsl_preview_3a \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_zsl_preview_3a_its \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_zsl_preview_3a_sn \
    libchromatix_daredevil_s5kgm1sp_back_tsp_i_zsl_video_3a \
    libchromatix_gc5035_a3_default_preview \
    libchromatix_gc5035_a3_default_video \
    libchromatix_gc5035_a3_hfr_120 \
    libchromatix_gc5035_a3_hfr_60 \
    libchromatix_gc5035_a3_hfr_90 \
    libchromatix_gc5035_common \
    libchromatix_gc5035_cpp_ds_chromatix \
    libchromatix_gc5035_cpp_hfr_120 \
    libchromatix_gc5035_cpp_hfr_60 \
    libchromatix_gc5035_cpp_hfr_90 \
    libchromatix_gc5035_cpp_liveshot \
    libchromatix_gc5035_cpp_preview \
    libchromatix_gc5035_cpp_snapshot \
    libchromatix_gc5035_cpp_us_chromatix \
    libchromatix_gc5035_cpp_video \
    libchromatix_gc5035_cpp_video_full \
    libchromatix_gc5035_default_video \
    libchromatix_gc5035_hfr_120 \
    libchromatix_gc5035_hfr_60 \
    libchromatix_gc5035_hfr_90 \
    libchromatix_gc5035_postproc \
    libchromatix_gc5035_preview \
    libchromatix_gc5035_snapshot \
    libchromatix_gc5035_video_full \
    libchromatix_gc5035_zsl_preview \
    libchromatix_gc5035_zsl_video \
    libdepthmapwrapper \
    libflash_pmic \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera_arcrtb \
    libmmcamera_atmel_at24c32e_eeprom \
    libmmcamera_csidtg \
    libmmcamera_daredevil_gc5035_aux_truly_ii \
    libmmcamera_daredevil_gc5035_aux_truly_ii_eeprom \
    libmmcamera_daredevil_gc8034_wide_byd_ii \
    libmmcamera_daredevil_gc8034_wide_byd_ii_eeprom \
    libmmcamera_daredevil_hi2021q_front_tsp_ii \
    libmmcamera_daredevil_hi2021q_front_tsp_ii_eeprom \
    libmmcamera_daredevil_hi556_aux_tsp_i \
    libmmcamera_daredevil_hi556_aux_tsp_i_eeprom \
    libmmcamera_daredevil_hi846_wide_txd_i \
    libmmcamera_daredevil_hi846_wide_txd_i_eeprom \
    libmmcamera_daredevil_s5k3t1sp_front_tru_ii \
    libmmcamera_daredevil_s5k3t1sp_front_tru_ii_eeprom \
    libmmcamera_daredevil_s5k3t1sp_front_tsp_i \
    libmmcamera_daredevil_s5k3t1sp_front_tsp_i_eeprom \
    libmmcamera_daredevil_s5kgm1sp_back_tly_ii \
    libmmcamera_daredevil_s5kgm1sp_back_tly_ii_eeprom \
    libmmcamera_daredevil_s5kgm1sp_back_tsp_i \
    libmmcamera_daredevil_s5kgm1sp_back_tsp_i_eeprom \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_interface \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_le2464c_eeprom \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_rohm_brcg064gwz_3_eeprom \
    libmmcamera_sat_test_lib \
    libmmcamera_stillmore_lib \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libois_bu63165 \
    libois_lc898122 \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libvidhance \
    vendor.qti.hardware.fingerprint@1.0 \
    android.hardware.gatekeeper@1.0-impl-qti \
    cdfinger.fingerprint.default \
    vendor.qti.hardware.soter@1.0-impl \
    libirisService \
    libiris_ioctl_wrapper \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    libqfp-service \
    libqtikeymaster4 \
    libremosaiclib \
    libsensorndkbridge \
    vendor.qti.hardware.soter@1.0 \
    vendor.trustonic.tee.tui@1.0 \
    vendor.trustonic.tee@1.0 \
    vendor.trustonic.teeregistry@1.0 \
    capi_v2_aptX_Classic \
    capi_v2_aptX_HD \
    libFastRPC_AUE_Forward_skel \
    libFastRPC_UTF_Forward_800h_skel \
    libFastRPC_UTF_Forward_Qtc2_skel \
    libFastRPC_UTF_Forward_Rohm_skel \
    libadsp_fd_skel \
    libadsp_hvx_add_constant \
    libadsp_hvx_skel \
    libedge_smooth_skel \
    libseemore_hexagon_skel \
    libvpp_svc_skel \
    vendor.qti.hardware.soter-V1.0-java \
    fingerprint \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.keymaster@4.0-service-qti \
    vendor.qti.hardware.soter@1.0-service \
    vendor.sw.swfingerprint@1.0-service \
    vendor.trustonic.tee@1.0-service \
    vendor.trustonic.teeregistry@1.0-service \
    mcDriverDaemon \
    mm-qcamera-app \
    mm-qjpeg-dec-test \
    mm-qjpeg-enc-test \
    mm-qomx-idec-test \
    mm-qomx-ienc-test \
    qfp-daemon \
    remosaic_daemon \
    sensors.qti \
    vendor.qti.hardware.soter@1.0-provision
